### ISSUE TITLE
Adapting @reactive to @vars syntax

### ISSUE THREAD

**Issue by jeremiedb** [GenieFramework/Stipple.jl#174] opened 2023-02-09 22:25 UTC
Following @AbhimanyuAryan advice on discord discussion, I'm having issue adapting the `@reactive` used to far to the `@vars` one.  

The following is working fine: https://github.com/jeremiedb/GenieExperiments.jl/blob/13a44594cb43c79369e6b05585f11f72dbf7a9a7/app/resources/UIDemo/PlotDemoController.jl#L59-L81

While the one adapted to `@vars` fails: https://github.com/jeremiedb/GenieExperiments.jl/blob/13a44594cb43c79369e6b05585f11f72dbf7a9a7/app/resources/UIDemo/PlotDemoController.jl#L38-L57

The resulting error is: 
```julia
julia> ┌ Error: 2023-02-08 17:15:38 MethodError: no method matching GenieExperiments.PlotDemoController.var"##MyModel!#313"()
│ Stacktrace:
```

I followed instruction found in `?Stipple.@vars`, and accordingle removed the reactive `R{...}` type wrapping. It however appears like there's something else required to perform the conversion? @hhaensel

**Comment by hhaensel** [comment] 2023-02-10 01:10
You did everything right. The code runs for me without problems. I'm on Stipple 0.25.19.

**Comment by jeremiedb** [comment] 2023-02-10 04:34
Did you actually commented out the `@reactive` code block and instead uncommented the `@vars` one? 
Also, issue isn't raised if simply opening the app, but needs to go to http://127.0.0.1:8002/plotdemo (sorry, I might not have been cleared about that). 

I've just made a refrsh of the packages, and I can still reproduce the error. I'm on Julia 1.8.5, Windows.
Current main branch of https://github.com/jeremiedb/GenieExperiments.jl is up to date with the following: 

```julia
(GenieExperiments) pkg> st
Project GenieExperiments v0.2.0
Status `C:\Users\jerem\OneDrive\JuliaComputing\GenieExperiements.jl\Project.toml`
  [336ed68f] CSV v0.10.9
  [aaaa29a8] Clustering v0.14.3
  [a93c6f00] DataFrames v1.4.4
  [c43c736e] Genie v5.15.0
  [6d011eab] Inflector v1.0.1
  [e6f89c97] LoggingExtras v1.0.0
  [a03496cd] PlotlyBase v0.8.19
  [ca7969ec] PlotlyLight v0.6.1
  [91a5bcdd] Plots v1.38.4
  [ce6b1742] RDatasets v0.7.7
  [2913bbd2] StatsBase v0.33.21
  [4acbeb90] Stipple v0.25.19
  [ec984513] StipplePlotly v0.13.2
  [a3c5d34a] StippleUI v0.21.2
  [ade2ca70] Dates
  [56ddb016] Logging
```

**Comment by hhaensel** [comment] 2023-02-10 07:58
I could reproduce the error, but I don't understand what happens. It seems that two model types have been generated, which I wouldn't expect. The latest one doesn't have proper keyword syntax attached. Maybe some point with Revise ...
Not easy to track.

**Comment by hhaensel** [comment] 2023-02-10 15:45
It was definitely a Revise issue. I refactored `@vars` to get rid of the stackoverflow error during loading.
and I refactored `@type` to ignore automatic code calls from Revise.
Please checkout the latest master.

**Comment by hhaensel** [comment] 2023-02-10 18:48
I should be more precise, Revise seems to call single lines of macro code for its analysis. That's at least my current understanding. Instead of a storage it passes an empty expression. That can be easily detected and the type generation is suppressed.

**Comment by hhaensel** [comment] 2023-02-10 20:52
I should be more precise, Revise seems to call single lines of macro code for its analysis. That's at least my current understanding. Instead of a storage it passes an empty expression. That can be easily detected and the type generation is now suppressed.

**Comment by jeremiedb** [comment] 2023-02-11 15:17
The issue appears solved with the fix on master. 
I'm not familiar enough with Revise to judge if the root cause is properly addressed, but end result looks legit. Thanks for the quick turnaround!

**Comment by ms10596** [comment] 2023-02-12 11:26
When will the fix be released? Currently, I'm installing stipple using `add Stipple#master`.

**Comment by hhaensel** [comment] 2023-02-12 23:44
> When will the fix be released
Now

**Comment by hhaensel** [comment] 2023-02-14 12:26
> I'm not familiar enough with Revise to judge if the root cause is properly addressed
I also was not sure whether Revise was the culprit, but it is.

Save the follwoing content to a file, say `ReviseTest.jl`
```julia
module MacroDefinition

export @test

macro test(expr)
    println("test start: ", expr)
    quote
        println("test quote start: ", $expr)
        local output = quote
            $$expr 
        end
        local output = quote end
        output.args = [$expr]

        eval(quote
            println("test eval: ", $output, "\n")
        end)
    end |> esc
end

end


module MacroCall

using Main.MacroDefinition

@test 2

end
```
and call it in two ways:
```julia
julia> include("ReviseTest.jl")
test start: 2      
test quote start: 2
test eval: 2
```
and
```julia
julia> using Revise; Revise.includet("ReviseTest.jl")
test start: 2      
test quote start: 2
test eval: 2       

test start: 2
test eval: nothing
```
We can use this fact to our advantage, because we can prevent additional model generation.
In the next version of Stipple I will add an explanatory comment.

**Comment by hhaensel** [comment] 2023-02-16 15:34
@jeremiedb If you're ok with the solution, you may close the issue.

**Closed** 2023-02-16 17:32 UTC
