### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by szafna** [GenieFramework/Stipple.jl#5] opened 2020-08-23 11:04 UTC
Stipple looks really promising. Honestly, I am a bit lost without documentation. Any near term plan it?

**Comment by essenciary** [comment] 2020-08-23 20:30
@szafna Yes, API, features and docs are WIP. A few weeks hopefully.

**Comment by hhaensel** [comment] 2020-08-25 09:07
Similar impression for me!
Stipple looks like a great package. It is really fast and responsive but difficult to understand from the examples only.

I am particularly confused by the many `using` statements like
```
using StippleUI, StippleUI.Table, StippleUI.Range, StippleUI.BigNumber, StippleUI.Heading, StippleUI.Dashboard
using StippleCharts, StippleCharts.Charts

import StippleUI.Range: range
```

Furthermore, I was surprised to see `using Revise` in the `StippleCharts.jl`

If you could comment on the concept, that would probably be helpful for many potential users.

**Comment by essenciary** [comment] 2020-08-25 10:05
@hhaensel For sure, good docs are a must. The demos are rather artifacts of the recent JuliaCon presentation and the best we have atm.    

Not sure what is surprising about the `using` statements and about `Revise`?

**Comment by hhaensel** [comment] 2020-08-27 10:55
I saw your presentation of the JuliaCon and found that the demo was quite impressive.

> Not sure what is surprising about the using statements and about Revise?

- I was surprised that you split your code in so many sub-modules which all import the main module, and not just simply include all UI-Elements.
- I never used Revise within a module to track changes of files. I always understood it rather as a development/debugger tool. Do you use it to make the server responsive to config changes without restart?
- Is it really necessary to include `using Revise` in all modules? Wouldn't it be sufficient to include it at the beginning of Genie and in those modules that use `Revise.track()`?
- After the first `using Revise` all other packages under development are also being tracked. Isn't that kind of an overkill? Maybe just tracking the config files would be sufficient?

Please don't get me wrong, I don't want to teach or anything, I just want to understand your package in the first place, because I think it could be a very important part of the Julia world.

**Comment by essenciary** [comment] 2020-08-27 11:30
@hhaensel Absolutely no offense, always looking to learn. The project is very early stage so the API is highly experimental. I see 2 points: 
1 - the elements are not exported
2 - the elements are wrapped in modules

Re #1 that can be easily addressed by (re)exporting them from Stipple. I prefer to not optimize prematurely. I'm sure down the line the pros and cons will become clearer. 
Re #2 I think it's best as components can define types, specialize methods in Stipple. Are there pros for not using modules for components? 

Re Revise I agree with you. The issue is, for me it's been very hit and miss. When I develop Stipple it's done within yet another app and many times Revise doesn't pick the changes within StippleUI (there's many levels of nested developed packages). So I tend to add it everywhere more out of desperation :) I think it's worth removing the Revise usage from everywhere and measuring if that affects code reloading and if improves performance - this should be consolidated, tips/commits welcomed :)

**Comment by hhaensel** [comment] 2020-08-28 11:59
@essenciary 
I never developed full-fledged apps with Julia, so I might be the wrong person to optimise your code ;-)
But if I look at other packages like WebIO there are no dependencies the user needs to load with `using ...`.
I don't see an advantage of using modules over including code. It rather make things simpler as you don't have to import all depending packages.

Concerning Revise I think it is best not to use it at all (it does run if you uncomment all imports!). I also think in terms of security it is better not to have code automatically executed as soon as a file changes. But you would need to change some load procedures...

**Comment by hhaensel** [comment] 2020-08-28 12:02
Here I place a demo snippet for an x-y plot, which might be part of a documentation

```
# Stipple x-y Line Plot
using Genie, Genie.Router, Genie.Renderer.Html
using Stipple, StippleUI, StippleCharts, StippleCharts.Charts

function Stipple.render(po::Dict, fieldname::Union{Symbol,Nothing} = nothing)
  s = replace(Genie.Renderer.Json.JSONParser.json(po), "\"undefined\""=>"undefined")
  # sometimes it is necessary to supply arguments without quotes in the JSON string,
  # e.g. functions or objects:
  # implement suppression of quotes if value string starts and ends with '%'
  s = replace(s, r"\"%(.+)%\"" => s"\1")
  # automatic suppression of quotes if a pure function is supplied as string value
  s = replace(s, r"\"(function\(.+?)(?<!\\)\"" => s"\1")
end

OptDict = Dict{Symbol, Any}
opts(;kwargs...) = OptDict(kwargs...)

const plot_opts_dict = OptDict(
  :chart => OptDict(:type => :line),
  :xaxis => OptDict(:type => :numeric),
  :yaxis => OptDict(:min => -5, :max => 5, :tickAmount => 10,
                    :labels => OptDict(:formatter => "function(val, index) { return val.toFixed(1); }")
            )
)

const plot_colors = ["#72C8A9", "#BD5631"]

xx = range(0, 4π, length=200) |> collect

Base.@kwdef mutable struct HHPage <: ReactiveModel
  name::R{String} = "World"
  a::R{Float64} = 1.0
  b::R{Float64} = 0.0
  c::R{Float64} = 0.0
  plot_data::R{Vector{PlotSeries}} = [PlotSeries("Sine", PlotData(zip(xx, a .* sin.(xx .- b) .+ c) |> collect))]
  # three different possibilites of supplying plot options:
  # original implementation (doesn't work for lineplots as too many options are supplied)
  plot_options::PlotOptions = PlotOptions()
  # implementation via Dict
  plot_options_dict::OptDict = plot_opts_dict
  # implementation via raw json String
  plot_options_json::AbstractString = Stipple.render(plot_opts_dict)
end

Stipple.register_components(HHPage, StippleCharts.COMPONENTS)

model = Stipple.init(HHPage)

# update plot_data when a, b or c are changed
Base.map!(model.plot_data, model.a, model.b, model.c) do a, b, c
  @info a, b, c
  return [PlotSeries("Sine", PlotData(zip(xx, a .* sin.(xx .- b) .+ c) |> collect))]
end

function ui()
  page(
    root(model), class="container", [
      h1(["Hello ", span("", Stipple.@text(:name)), "!"])

      p(["What is your name? ", Html.input("", placeholder="Type your name", @bind(:name))])
      p(["a: ", Html.input("", placeholder="Amplitude", @bind(:a))])
      p(["b: ", Html.input("", placeholder="Amplitude", @bind(:b))])
      p(["c: ", Html.input("", placeholder="Amplitude", @bind(:c))])
      Html.div(plot(:plot_data; options=:plot_options_json), style = "width: 400px")
    ], title = "Stipple x-y ApexChart"
  ) |> html
end

route("/", ui)

up()
```

**Comment by essenciary** [comment] 2020-08-28 12:16
@hhaensel Thanks!

Re modules, if I understand your point, it's a matter of scoping (users have to bring the definitions into scope by `using`). The scope can be modified by (re)exporting the definitions. It's a simple change that can be done at any time in minutes. Without pros or cons on either side I'd rather not decide at this point - we need more data. 

Revise is not needed in Stipple so we should just remove it (it's there just to help me while developing). It is however used by Genie to provide auto-loading of user code (so re-loading the user app while developing just works).

**Comment by hhaensel** [comment] 2020-08-28 16:16
> It is however used by Genie to provide auto-loading of user code (so re-loading the user app while developing just works).

I also eliminated all Revise statements from Genie and it still works ...
Also for Genie, I am not so sure whether unchecked code reloading is a good idea...
Maybe @timholy (the author of Revise) has some good advice here?

**Comment by essenciary** [comment] 2020-08-29 10:53
> I also eliminated all Revise statements from Genie and it still works ...
What exactly worked and under what conditions? Certainly code reload in a Genie app can't work if there is no Revise on the system. So somewhere, somehow, code gets revised. 

> Also for Genie, I am not so sure whether unchecked code reloading is a good idea...
What do you have in mind?

**Comment by hhaensel** [comment] 2020-09-01 06:51
>>Also for Genie, I am not so sure whether unchecked code reloading is a good idea...

>What do you have in mind?

I think for code reloading it would be good to have a well-defined set of files that are to be checked for changes. However, `Revise` checks all subsequently loaded packages for changes and executes them. I don't know whether it is possible to suppress automatic reloading for all packages and allow only specific files (and packages, if needed).
But, again, I think I am a weak mentor for a deeper discussion and it is rather a gutt feeling that I have. I would recommend to discuss the topic - if you are interested - with @timholy. You know Genie very well, as he does know Revise.

**Comment by hhaensel** [comment] 2020-09-01 08:23
Meanwhile, I played a bit with the dashboard and I am really happy with the output that can be achieved.
(Can you help, where to place the logo file, if I run the script below straight from the REPL?)

```
# Stipple x-y Line Plot
using Stipple
using StippleCharts, StippleCharts.Charts
using StippleUI, StippleUI.Range, StippleUI.Heading, StippleUI.Dashboard, StippleUI.FormInput
using Genie, Genie.Router, Genie.Renderer.Html

function Stipple.render(po::Dict, fieldname::Union{Symbol,Nothing} = nothing)
    s = replace(Genie.Renderer.Json.JSONParser.json(po), "\"undefined\""=>"undefined")
    # sometimes it is necessary to supply arguments without quotes in the JSON string,
    # e.g. functions or objects:
    # implement suppression of quotes if value string starts and ends with '%'
    s = replace(s, r"\"%(.+)%\"" => s"\1")
    # automatic suppression of quotes if a pure function is supplied as string value
    s = replace(s, r"\"(function\(.+?)(?<!\\)\"" => s"\1")
end

OptDict = Dict{Symbol, Any}
opts(;kwargs...) = OptDict(kwargs...)

const plot_opts_dict = OptDict(
    :chart => OptDict(:type => :line),
    :xaxis => OptDict(:type => :numeric),
    :yaxis => OptDict(:min => -5, :max => 5, :tickAmount => 10,
                      :labels => OptDict(:formatter => "function(val, index) { return val.toFixed(1); }")
              )
)

xx = Base.range(0, 4π, length=200) |> collect

Base.@kwdef mutable struct HHDashboard <: ReactiveModel
    name::R{String} = "World"
    a::R{Float64} = 1.0
    b::R{Float64} = 0.0
    c::R{Float64} = 0.0
    plot_data::R{Vector{PlotSeries}} = [PlotSeries("Sine", PlotData(zip(xx, a .* sin.(xx .- b) .+ c) |> collect))]
    plot_options_dict::OptDict = plot_opts_dict
end

Stipple.register_components(HHDashboard, StippleCharts.COMPONENTS)
model = Stipple.init(HHDashboard)

# update plot_data when a, b or c are changed
Base.map!(model.plot_data, model.a, model.b, model.c) do a, b, c
        @info "amplitude: $a, phase: $b, offset: $c"
        return [PlotSeries("Sine", PlotData(zip(xx, a .* sin.(xx .- b) .+ c) |> collect))]
end

function ui()
    dashboard(root(model), class="container", [
        heading("Stipple x-y Line Plot"),
        row(
            cell(class="st-module", h2(["Hello ", span("", Stipple.@text(:name)), "!"]))
        ),
        row(
            cell(class="st-module", row([
                cell(class="st-br", style="padding-right: 20px;", [
                    h5("What is your name?"),
                    textfield(:name, placeholder="type your name", label="Name", outlined="", filled="")
                ]),
                cell(class="st-br", style="padding-left: 20px;", [
                    h5("Sine oder Cosine?"),
                    row([
                        cell(size=4, h6("Amplitude")),
                        cell(slider( 0:0.01:5, @data(:a); markers=true, label=true))
                    ]),
                    row([
                        cell(size=4, h6("Phase")),
                        cell(slider( 0:0.01:5, @data(:b); markers=true, label=true))
                    ]),
                    row([
                        cell(size=4, h6("Offset")),
                        cell(slider( -3:0.01:3, @data(:c); markers=true, label=true))
                    ])
                ])
            ]))
        ),
        row(
            cell(class="st-module", plot(:plot_data; options=:plot_options_dict))
        ),
        # make a nice bottom section
        row("&nbsp;")
    ], title = "Stipple x-y ApexChart") |> html
end

route("/", ui)

up()
```
![image](https://user-images.githubusercontent.com/31985040/91824042-6da4da00-ec3a-11ea-8f7c-f08d246992e8.png)

**Comment by touchft** [comment] 2021-01-02 13:17
Stipple is great! Julia is a great tool for big data. Now we have great tool for data visualization on web !

**Comment by junglegobs** [comment] 2021-01-10 20:21
It's cool that this exists in Julia, but I have to say that I find it incredibly difficult to understand how to do anything other than just copy the examples. Even e.g. `?ReactiveModel` doesn't provide any useful hints!

**Comment by essenciary** [comment] 2021-01-11 08:54
@junglegobs Sorry about that, 100% agree - good docs is top of the priority list!

**Comment by jonniedie** [comment] 2021-04-23 00:29
I'd like to chime in here to request docs as well. A coworker of mine is making a dashboard for one of our simulations and I recommended checking out Stipple. He wasn't able to figure out how to use it without docs, so he ended up using Dash instead, which has proven to be really hard to work with (everything is done with callbacks using strings to call to internal variables). Stipple, on the other hand, looks really nice to use, we just don't know how yet :-)

**Comment by essenciary** [comment] 2021-04-23 07:28
Made some good progress with documenting the code in Stipple.jl (so we can now use Julia's REPL help mode) but there's still more to do indeed. Working on it. 

@jonniedie can you provide some insight into what kind of docs would be best? API docs? Recipes to connect pieces? Guides to building full apps? What are the issues (developing, deploying)? What is a good documentation in your/your friend's opinion? Can Dash be used as a reference? What was good in Dash's docs that we should copy and what could be improved?

**Comment by jonniedie** [comment] 2021-04-23 14:17
What I like about the Dash docs is how it provides a walk-through tutorial that assumes no knowledge of web development. This is important because people who want to make dashboards are typically scientists/engineers/data scientists who just want to show their data in an interesting way and are using a dashboard framework because they can't afford to take the time to learn web development.

So in the Dash docs, they start with a concept--let's use their tutorial on [callbacks](https://dash.plotly.com/basic-callbacks) for example--provide a runnable example, then walk through every step of the example showing what each piece did. What does `@app.callback` do? Oh nice, they tell us right away. And they even put some drop-down text there if we want to learn in more detail.

Stipple has some nice demos, but without a tutorial walking through each part and telling me "this is what this thing does", I have no idea what I'm supposed to be doing.

Taking the most basic [Hello Stipple](https://github.com/GenieFramework/StippleDemos/blob/master/HelloStipple.jl) example, here is how I would read it:

**Line 2**: Okay, in addition to `Stipple`, we're importing something called `StippleCharts`. I don't see any charts here, though. What is this module exporting that we're using here?

**Line 4**: We are defining our own struct that inherits from `ReactiveModel`. That must make it able to interact with the rest of the dashboard. Do I need to make a new struct for every element type I have?

**Line 5**: What is `R{String}`? I can probably infer that `R` is some type of observable wrapper, but someone who had never encountered observables (most people who are writing a dashboard for the first time) wouldn't know that. Also, we are giving it a normal string value as the default argument, so I assume it promotion is in place somewhere to promote `T` to `R{T}`? That could use some explaining for beginners.

**Line 13**: What's a `vm`? Virtual machine? Why would that be here? 

**Lines 17, 19, and 22**: What is `h1`? What is `span`? What is `p`? Are these html things? I don't want to have to pull up html docs separately and try to guess which parts Stipple implements and which it doesn't. It would be nice if Stipple's docs had a list of "here are the html functions we export and here's what they do".

**Lines 19 and 24**: What does `@text` do? Does it just get the value of the name?

**Line 35**: Why are we creating a random number between 8000 and 9000? Can't Stipple just do that for us?

etc. If it seems like I'm being too obtuse here, I partially am. But this is about the level that most new users writing their first dashboard will be at. It's especially hard if they are also new to Julia and have to figure out which parts are "Julia things" they have to learn and which parts are "Stipple things" they have to learn.

Anyway, I hope this is all taken as constructive. I've been excited about Stipple since before you demoed it at JuliaCon last year.

**Comment by hhaensel** [comment] 2021-04-23 16:31
Just want to advertise that we are giving an[ online presentation on Stipple 3rd May](https://www.meetup.com/de-DE/Julia-User-Group-Munich/events/277664916/). We will showcase the new model API that is already available in the current master, explain the StippleUI API and end with some demos.
Be sure not to miss it if you are longing for docs 😉

**Comment by Boxylmer** [comment] 2021-04-26 16:55
Just want to give my +1 for docs as far as incoming users go. Our lab needs a quick and dirty front end for interfacing with some complex chemical models plus potentially something to visualize live data streams remotely (but still in a private network), and Stipple seems perfect for both!

Definitely also had struggles with the demos but couldn't quite sort out what was due to being new to Julia or new to Stipple. Great project! Hope I can contribute at some point.

**Comment by zsz00** [comment] 2021-04-30 09:33
Stipple.jl  is same to streamlit, 
the documents can reference to https://docs.streamlit.io/en/stable/

**Comment by zsz00** [comment] 2021-07-10 14:25
Is there any progress on the document writing?

**Comment by TobiasSkovgaardJepsen** [comment] 2021-08-02 17:07
@jonniedie Your comment accurately describes my experience. I am a computer science researcher with limited experience with developing web applications from several years ago. My experience with anything resembling reactive web applications is even more limited.

In addition to @jonniedie's comments, I will add that the distinction between Stipple.jl and "regular" Genie.jl is unclear when looking at the uncommented examples in the README. I am unsure when I am looking at code that is simply used to style the web page versus code that connects page elements to the model. I think keeping the two separate would make picking up Stipple.jl easier. 

The kind of documentation that would help me would focus less on concrete examples and more on the architecture of Stipple.jl. I would like to see a basic tutorial that covers what the basic building blocks for Stipple.jl are and how to define them. I think just taking the two examples from the README and transforming them into a Getting Started page by essentially commenting them extensively would go a long way to get potential users such as myself started with Stipple.jl.

**Comment by Xinyu-Wu-0000** [comment] 2021-09-25 08:32
Really hoping there can be a detailed documentation.

**Comment by zsz00** [comment] 2022-01-09 16:03
Is there any progress on the document writing? 
what is the doc page url ?

**Comment by AbhimanyuAryan** [comment] 2022-01-09 18:06
@zsz00 its the top priority of us this month.  Please keep up with our discord updates

**Comment by zsz00** [comment] 2022-02-28 08:46
文件编写是否有任何进展？
什么是文档页面网址？

**Comment by AbhimanyuAryan** [comment] 2022-02-28 08:52
@zsz00 we are currently in process of testing Stipple after testing we will proceed to docs. For Stipple examples you can look at: https://github.com/GenieFramework/StippleDemos

For component wise examples. We are writing tests for them which can also look at here: https://github.com/GenieFramework/StippleUI.jl/tree/tests/test/components

**Comment by AbhimanyuAryan** [comment] 2022-04-22 07:55
@zsz00 we have release v1 for Stipple, StippleUI docs. Feel free to create issues, pull request and drop your valuable feedback as we are continuously improving docs: https://www.genieframework.com/docs/

**Comment by zsz00** [comment] 2022-04-22 09:11
Thank you for your great work!!

**Comment by camilodlt** [comment] 2022-05-22 17:08
It would be really nice to have tutorials and walkthroughs. The current documentation is great for reference but it's not easy for getting started. 
Thank you for your work!

**Comment by essenciary** [comment] 2022-05-23 09:35
@camilodlt 100% that we need guides and walkthroughs. We have some in the pipeline but any contributions from users would also be greatly appreciated and would help a lot. We're more than happy to host user created guides on the official docs website.

**Closed** 2022-08-02 18:19 UTC
Labels: documentation
